
spring.application.name=delivery-service

spring.mongodb.uri=mongodb+srv://ridika:<db_password>@cluster0.uh1vcpl.mongodb.net/?appName=Cluster0
spring.mongodb.database=foodexpress_delivery

app.auth.mongodb.database=foodexpress_auth
