
spring.application.name=authentication-service

spring.mongodb.uri=mongodb+srv://ridika:Ridika2004@cluster0.uh1vcpl.mongodb.net/?appName=Cluster0
spring.mongodb.database=foodexpress_auth

# ─── JWT ───────────────────────────────────────────────
# Minimum 32 bytes for HS256
app.jwt.secret=foodexpress-auth-jwt-secret-key-should-be-changed-in-prod-2024
app.jwt.expiration-ms=86400000