server.port=9001
spring.application.name=authentication-service

spring.data.mongodb.uri=mongodb+srv://zannatuladonsabiha_db_user:7qaIAdkImgkTShuC@cluster0.l0wixyx.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=foodexpress_auth

# ─── JWT ───────────────────────────────────────────────
# Minimum 32 bytes for HS256
app.jwt.secret=foodexpress-auth-jwt-secret-key-should-be-changed-in-prod-2024
app.jwt.expiration-ms=86400000