server:
  port: 9002
spring:
  application:
    name: RESTAURANT-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://zannatuladonsabiha_db_user:7qaIAdkImgkTShuC@cluster0.l0wixyx.mongodb.net/foodexpress_restaurant?retryWrites=true&w=majority&appName=Cluster0

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost