
spring.application.name=restaurant-service

spring.mongodb.uri=mongodb+srv://zannatuladonsabiha_db_user:7qaIAdkImgkTShuC@cluster0.l0wixyx.mongodb.net/foodexpress_restaurant?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.database=foodexpress_restaurant

